apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.deployment.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
    spec:
      containers:
        - name: {{ .Values.app.container.name }}
          image: {{ .Values.app.container.image.name }}
          imagePullPolicy: {{ .Values.app.container.image.pull.policy }}
          ports:
            - containerPort: {{ .Values.app.port.http.targetPort }}
              name: webapp
            - containerPort: {{ .Values.app.port.management.targetPort }}
              name: actuator
          env:
            - name: DATABASE_URL
              value: {{ .Values.app.env.database.url }}
            - name: DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.app.env.database.secret.name }}
                  key: POSTGRES_USER
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.app.env.database.secret.name }}
                  key: POSTGRES_PASSWORD
            - name: SPRING_PROFILES_ACTIVE
              value : {{ .Values.app.env.spring.profiles.active }}
          envFrom:
            - secretRef:
                name: oauth-rsa-secret


# service type loadbalancer
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.service.name }}
spec:
  ports:
    - name: http
      port: {{ .Values.app.port.http.port }}
      targetPort: {{ .Values.app.port.http.targetPort }}
      protocol: TCP
    - name: management
      port: {{ .Values.app.port.management.port }}
      targetPort: {{ .Values.app.port.management.targetPort }}
      protocol: TCP
  type: {{ .Values.app.service.type }}
  selector:
    app: {{ .Values.app.name }}