security:
  oauth2:
    resource:
      filter-order: 3
debug: true
management:
  server:
    port: 9001
  endpoints:
    web:
      exposure:
        include: "*"
---

spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:h2:mem:localdb
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
admin:
  client:
    id: local-admin
    secret: $2a$10$5lI9OvVh27q7Bkn7hg2Tv.GCTPHwJGJT1yQ2jBJmqVgrF2Az/AeBu
user:
  client:
    id: local-user
    secret: $2a$10$fd3Te4dtTlCpdDS6owliY.Xhae4vbp/mYvEoR5mZNP93lKUqGPPRq

---

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
admin:
  client:
    id: dev-admin
    secret: $2a$10$5lI9OvVh27q7Bkn7hg2Tv.GCTPHwJGJT1yQ2jBJmqVgrF2Az/AeBu
user:
  client:
    id: dev-user
    secret: $2a$10$fd3Te4dtTlCpdDS6owliY.Xhae4vbp/mYvEoR5mZNP93lKUqGPPRq

---

spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
admin:
  client:
    id: admin
    secret: $2a$12$hJOEPAx7rPJvqsrPIscjQOwkP.d1OH//EGYo3lq6Gqx57hYbJ.Xdy
user:
  client:
    id: user
    secret: $2a$10$fd3Te4dtTlCpdDS6owliY.Xhae4vbp/mYvEoR5mZNP93lKUqGPPRq