spring:
  config:
    activate:
      on-profile: local
  security:
    oauth2:
      authorization-server:
        issuer: http://localhost:8080
        client:
          api-client:
            registration:
              client-id: local-api
              client-secret: "{noop}api123"
              client-authentication-methods: client_secret_basic
              authorization-grant-types: client_credentials
            token:
              access-token-time-to-live: 36000s
---

spring:
  config:
    activate:
      on-profile: dev
api:
  client:
    id: dev-api
    secret: $2a$10$5lI9OvVh27q7Bkn7hg2Tv.GCTPHwJGJT1yQ2jBJmqVgrF2Az/AeBu
jwt:
  signing-key: ${OAUTH_SIGNING_KEY}
  verifier-key: ${OAUTH_VERIFIER_KEY}

---

spring:
  config:
    activate:
      on-profile: prod
api:
  client:
    id: user-api
    secret: $2a$12$hJOEPAx7rPJvqsrPIscjQOwkP.d1OH//EGYo3lq6Gqx57hYbJ.Xdy
jwt:
  signing-key: ${OAUTH_SIGNING_KEY}
  verifier-key: ${OAUTH_VERIFIER_KEY}