version: "3.9"

services:
  postgres:
    image: postgres:14-alpine
    env_file: .env
    ports:
      - $SQLDB_LOCAL_PORT:$SQLDB_DOCKER_PORT
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=$SQLDB_ROOT_PASSWORD
      - POSTGRES_USER=$SQLDB_USER
      - POSTGRES_DB=$SQLDB_DATABASE

  app:
    depends_on:
      - postgres
    build:
      context: ..
      dockerfile: ./Dockerfile
    restart: on-failure
    env_file: .env
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:postgresql://postgres:$SQLDB_DOCKER_PORT/$SQLDB_DATABASE?useSSL=false",
        "spring.datasource.username" : "$SQLDB_USER",
        "spring.datasource.password" : "$SQLDB_ROOT_PASSWORD",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.PostgreSQLDialect",
        "spring.jpa.hibernate.ddl-auto" : "none"
      }'
      SPRING_PROFILES_ACTIVE: $SPRING_PROFILE
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true

volumes:
  db: