CREATE TABLE AUTHORITY (
   ID BIGSERIAL PRIMARY KEY,
   NAME VARCHAR(255) UNIQUE,
   CREATED_TIME TIMESTAMP NOT NULL default localtimestamp,
   CREATED_BY VARCHAR(255) NOT NULL default 'system',
   UPDATED_TIME TIMESTAMP,
   UPDATED_BY VARCHAR(255)
);

CREATE TABLE USER_DETAILS (
   ID BIGSERIAL PRIMARY KEY,
   USER_NAME VARCHAR(255) NOT NULL UNIQUE,
   PASSWORD VARCHAR(255) NOT NULL,
   ACCOUNT_EXPIRED BOOLEAN NOT NULL default FALSE,
   ACCOUNT_LOCKED BOOLEAN NOT NULL default FALSE,
   CREDENTIALS_EXPIRED BOOLEAN NOT NULL default FALSE,
   ENABLED BOOLEAN NOT NULL default TRUE,
   CREATED_TIME TIMESTAMP NOT NULL default localtimestamp,
   CREATED_BY VARCHAR(255) NOT NULL default 'system',
   UPDATED_TIME TIMESTAMP,
   UPDATED_BY VARCHAR(255)
);

CREATE TABLE USER_AUTHORITIES (
   USER_ID BIGINT NOT NULL,
   AUTHORITY_ID BIGINT NOT NULL,
   CREATED_TIME TIMESTAMP NOT NULL default localtimestamp,
   CREATED_BY VARCHAR(255) NOT NULL default 'system',
   UPDATED_TIME TIMESTAMP,
   UPDATED_BY VARCHAR(255),
   PRIMARY KEY (USER_ID, AUTHORITY_ID),
   FOREIGN KEY (AUTHORITY_ID) REFERENCES AUTHORITY,
   FOREIGN KEY (USER_ID) REFERENCES USER_DETAILS
);

INSERT INTO AUTHORITY(ID, NAME) VALUES (1, 'ADMIN_ROLE');
INSERT INTO AUTHORITY(ID, NAME) VALUES (2, 'USER_ROLE');